version: "3"
services:
  docker_mysql:
    image: mysql:latest
    container_name: mysql_container 
    ports:
      - "3377:3306"
    environment:
      MYSQL_ROOT_PASSWORD: cxgs7102
      MYSQL_DATABASE: proyectoFinal
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  docker_redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    